Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  # config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

# TODO: These images all crash on macOS VB!
  # config.vm.box = "freebsd/FreeBSD-11.1-RELEASE"
  # config.vm.box_version = "2017.07.21"
  config.vm.box = "kingcdavid/freebsd-11-RELEASE"
  config.vm.box = "bento/freebsd-11.0"

  # config.ssh.shell = "sh"
  # config.vm.base_mac = "080027D14C66"
  #
  # config.vm.provider :virtualbox do |vb|
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  #   vb.customize ["modifyvm", :id, "--cpus", "1"]
  #   vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  #   vb.customize ["modifyvm", :id, "--audio", "none"]
  #   vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  #   vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  # end
end
