# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "freebsd/FreeBSD-11.1-RELEASE"
  config.vm.box_version = "2017.07.21"
  config.vm.base_mac = "080027D24C09"
  
    # Necessary for official FreeBSD images
    config.ssh.shell = "sh"
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  config.vm.provision "shell", path: "provision.sh", env: {"JENKINS_SLAVE_NAME" => "TheSlave", "JENKINS_SLAVE_SECRET" => "TheSecret", "JENKINS_URL" => "http://1.2.3.4"}
end
